config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: "home#index"

  resources :sales, only: [:index]
  resources :catalogue, only: [:index]
  resources :suppliers, only: [:index, :new, :create, :show]

  namespace :catalogue do
    resources :suppliers, only: [:index, :new, :create, :show] do
      # collection do
      #   get :select
      #   post :selected
      # end
      resources :products, only: [:index, :new, :create]
    end
  end
  resources :inventories, only: [:index]
end

app/controllers/catalogue/products_controller.rb
# frozen_string_literal: true

class Catalogue::ProductsController < ApplicationController
  before_action :sanitize_params, only: [:create]
  before_action :product_with_sku_code, only: [:new]

  def new; end

  def create
    @product = supplier.products.new(product_params)
    if @product.save
      redirect_to catalogue_supplier_path(supplier.id)
    else
      render :new
    end
  end

  private

  def product
    @product ||= supplier.products.new
  end

  def product_with_sku_code
    product.sku_code = sku_code
    product
  end

  def sku_code
    @sku_code ||= @product.generated_sku
  end

  def sanitize_params
    params.require(:product).permit(:supplier_id, :accounting_code_id, :title, :description, :notes, :sku_code, :publish, :markup, :cost_price)

    params[:product]['markup'] = markup
    params[:product]['publish'] = publish
    params[:product]['cost_price'] = cost_price
  end

  def unmatched_params
    @unmatched_params ||= params.require(:product).extract!(:publish, :markup, :cost_price)
  end

  def cost_price
    (unmatched_params['cost_price'].gsub(/[^0-9,.]/, '').to_f * 100).to_i
  end

  def markup
    unmatched_params['markup'].gsub(/[^0-9]/, '')
  end

  def publish
    unmatched_params['publish'] == 'Yes'
  end

  def product_params
    params.require(:product).permit(:supplier_id, :accounting_code_id, :title, :description, :notes, :sku_code, :publish, :markup, :cost_price)
  end

  def supplier
    @supplier ||= Supplier.find_by(id: supplier_id)
  end

  def supplier_id
    @supplier_id = params['supplier_id']
  end
end

app/controllers/catalogue/suppliers_controller.rb
# frozen_string_literal: true

class Catalogue::SuppliersController < ApplicationController
  before_action :supplier, only: %i[index create]

  def index; end

  def show
    @supplier = existing_supplier(id: params['id'])
    @products = @supplier.products
  end

  def create
    if existing_supplier.present?
      redirect_to catalogue_supplier_path(existing_supplier.id)
    else
      flash.now.alert = 'Please select a supplier from the list'
      render :index
    end
  end

  private

  def supplier
    @supplier ||= Supplier.new
  end

  def existing_supplier(id: nil)
    supplier_id = id || supplier_params[:id]
    @existing_supplier = Supplier.find_by(id: supplier_id) if supplier_id.present?
  end

  def supplier_params
    params.require(:supplier).permit(:id)
  end
end

app/controllers/catalogue_controller.rb
# frozen_string_literal: true

class CatalogueController < ApplicationController
  def index; end
end

app/controllers/catalogues_controller.rb
# frozen_string_literal: true

class CataloguesController < ApplicationController
  def index; end
end

app/helpers/catalogue/products_helper.rb
# frozen_string_literal: true

module Catalogue::ProductsHelper
end

app/helpers/catalogue/suppliers_helper.rb
# frozen_string_literal: true

module Catalogue::SuppliersHelper
end

app/helpers/catalogues_helper.rb
# frozen_string_literal: true

module CataloguesHelper
end

app/views/catalogue/index.html.erb
<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
  <!--Card 1-->
  <div class="rounded overflow-hidden shadow-lg content-center">
    <!-- <img class="w-full" src="/mountain.jpg" alt="Mountain"> -->
    <div class="px-6 py-4">
      <div class="mb-4 text-3xl font-black">All Products</div>
      <p class="text-gray-700 text-base">
        Make changes to existing products, add new variants, print labels and remove products from sale or delete them.
      </p>
    </div>
    <div class="px-6 pt-4 pb-2">
      <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Continue</button>'.html_safe, new_catalogue_supplier_path %>
    </div>
  </div>
  <!--Card 2-->
  <div class="rounded overflow-hidden shadow-lg">
    <!-- <img class="w-full" src="/river.jpg" alt="River"> -->
    <div class="px-6 py-4">
      <div class="mb-4 text-3xl font-black">Products by Supplier</div>
      <p class="text-gray-700 text-base">
        Make changes to existing products for a specific supplier, add new variants, print labels and archive or remove products.
      </p>
    </div>
    <div class="px-6 pt-4 pb-2">
      <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Continue</button>'.html_safe, catalogue_suppliers_path %>
    </div>
  </div>
  <!--Card 3-->
  <div class="rounded overflow-hidden shadow-lg">
    <!-- <img class="w-full" src="/river.jpg" alt="River"> -->
    <div class="px-6 py-4">
      <div class="mb-4 text-3xl font-black">Suppliers</div>
      <p class="text-gray-700 text-base">
        Add a new suppliers details to Poskin or edit the details for an existing supplier in Poskin.
      </p>
    </div>
    <div class="px-6 pt-4 pb-2">
      <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Continue</button>'.html_safe, suppliers_path %>
    </div>
  </div>
</div>