config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: "home#index"

  resources :sales, only: [:index]
  resources :catalogue, only: [:index]
  resources :suppliers, only: [:index, :new, :create, :show]

  namespace :catalogue do
    resources :suppliers, only: [:index, :new, :create, :show] do
      # collection do
      #   get :select
      #   post :selected
      # end
      resources :products, only: [:index, :new, :create]
    end
  end
  resources :inventories, only: [:index]
end

app/models/accounting_code.rb
# frozen_string_literal: true

class AccountingCode < ApplicationRecord
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category_tag.rb
# frozen_string_literal: true

class CategoryTag < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/country.rb
# frozen_string_literal: true

class Country < ApplicationRecord
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  include ActionView::Helpers::NumberHelper

  belongs_to :supplier
  has_and_belongs_to_many :category_tags

  # Product.category_tags  #=> [<CategoryTag @name="Sports">, ...]
  # CategoryTag.products   #=> [<Product @name="UserA">, ...]
  # Product.category_tags.empty?

  scope :published, lambda {
    where(publish: true)
  }

  validates :accounting_code_id, :title, :description, :sku_code, :publish, :markup, presence: true

  validates :cost_price, presence: true, numericality: { greater_than_or_equal_to: 1, only_integer: true }

  def display_cost_price
    number_to_currency(format('%.2f', (cost_price.to_f / 100))) unless cost_price.nil?
  end

  def display_markup
    "#{markup}%" if markup.present?
  end

  def display_published
    publish ? 'Yes' : 'No'
  end

  def generated_sku
    candidate_sku = (SecureRandom.random_number(9e5) + 1e5).to_i
    generated_sku if Product.all.map(&:sku_code).include?(candidate_sku)
    candidate_sku
  end
end

app/models/product_attribute.rb
# frozen_string_literal: true

class ProductAttribute < ApplicationRecord
  has_and_belongs_to_many :variants
end

app/models/supplier.rb
# frozen_string_literal: true

class Supplier < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, :phone, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/tax_rate.rb
# frozen_string_literal: true

class TaxRate < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/variant.rb
# frozen_string_literal: true

class Variant < ApplicationRecord
  has_and_belongs_to_many :product_attributes
end

app/controllers/catalogue_controller.rb
# frozen_string_literal: true

class CatalogueController < ApplicationController
  def index; end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/sales_controller.rb
# frozen_string_literal: true

class SalesController < ApplicationController
  def index; end
end

app/controllers/suppliers_controller.rb
# frozen_string_literal: true

class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end

  def new
    @supplier = Supplier.new
    @gst_rates = TaxRate.all
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to catalogue_suppliers_path
    else
      render :new
    end
  end

  private

  def supplier_params
    params.require(:supplier).permit(:name, :email, :phone, :tax_rate_id, :address_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/catalogues_helper.rb
# frozen_string_literal: true

module CataloguesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/inventories_helper.rb
# frozen_string_literal: true

module InventoriesHelper
end

app/helpers/sales_helper.rb
# frozen_string_literal: true

module SalesHelper
end

app/helpers/suppliers_helper.rb
# frozen_string_literal: true

module SuppliersHelper
end

app/helpers/tailwind_form_builder.rb
# frozen_string_literal: true

class TailwindFormBuilder < ActionView::Helpers::FormBuilder
  delegate :tag, :safe_join, to: :@template

  def text_field(method, opts = {})
    default_opts = { class: 'mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50' }
    merged_opts = default_opts.merge(opts)
    super(method, merged_opts)
  end

  def input(method, options = {})
    @form_options = options
    object_type = object_type_for_method(method)

    input_type = case object_type
                 when :date then :string
                 when :integer then :string
                 else object_type
                 end

    override_input_type = if options[:as]
                            options[:as]
                          elsif options[:collection]
                            :select
                          end

    send("#{override_input_type || input_type}_input", method, options)
  end

  def submit_button(text, opts: {})
    classes = (opts.delete(:class) || opts.delete('class') || '').split
    classes << 'btn btn-primary'
    # classes << "btn-primary" unless classes.any?{|c| c =~ /^btn-/}
    @template.button_tag(text, opts.merge(class: classes.uniq.join(' ')))
  end

  private

  def form_group(method, options = {}, &block)
    tag.div class: "form-group #{method}" do
      safe_join [
        block.call,
        hint_text(options[:hint]),
        error_text(method)
      ].compact
    end
  end

  def collection_input(method, options, &block)
    form_group(method, options) do
      safe_join [
        label(method, options[:label]),
        block.call
      ]
    end
  end

  def has_error?(method)
    return false unless @object.respond_to?(:errors)

    @object.errors.key?(method)
  end

  def hint_text(text)
    return if text.nil?

    tag.small text, class: 'form-text text-muted'
  end

  def error_text(method)
    return unless has_error?(method)

    tag.div(@object.errors[method].join('<br />').html_safe, class: 'invalid-feedback')
  end

  def select_input(method, options = {})
    value_method = options[:value_method] || :to_s
    text_method = options[:text_method] || :to_s
    input_options = options[:input_html] || {}

    multiple = input_options[:multiple]

    collection_input(method, options) do
      collection_select(method, options[:collection], value_method, text_method, options, merge_input_options({ class: "#{unless multiple
                                                                                                                            'custom-select'
                                                                                                                          end} form-control #{if has_error?(method)
                                                                                                                                                'is-invalid'
                                                                                                                                              end}" }, options[:input_html]))
    end
  end

  def object_type_for_method(method)
    result = if @object.respond_to?(:type_for_attribute) && @object.has_attribute?(method)
               @object.type_for_attribute(method.to_s).try(:type)
             elsif @object.respond_to?(:column_for_attribute) && @object.has_attribute?(method)
               @object.column_for_attribute(method).try(:type)
             end

    result || :string
  end

  def merge_input_options(options, user_options)
    return options if user_options.nil?

    # TODO: handle class merging here
    options.merge(user_options)
  end
end

app/views/home/_old_index.html.slim
.max-w-lg.mx-auto.mt-16.text-center.max-w-sm.rounded.overflow-hidden.shadow-lg.p-10
  h1.mb-4.text-3xl.font-black
      | Welcome to Poskin!!
  p.text-lg.leading-snug
      | Let's do some stuff.

app/views/home/index.html.erb
<% if user_signed_in? %>
  <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
    <!--Card 1-->
    <div class="rounded overflow-hidden shadow-lg content-center">
      <!-- <img class="w-full" src="/mountain.jpg" alt="Mountain"> -->
      <div class="px-6 py-4">
        <div class="mb-4 text-3xl font-black">Sell</div>
        <p class="text-gray-700 text-base">
          Point of Sale app, raise a new sale and create record for a new Customer
        </p>
      </div>
      <div class="px-6 pt-4 pb-2">
        <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Continue</button>'.html_safe, sales_path %>
      </div>
    </div>
    <!--Card 2-->
    <div class="rounded overflow-hidden shadow-lg">
      <!-- <img class="w-full" src="/river.jpg" alt="River"> -->
      <div class="px-6 py-4">
        <div class="mb-4 text-3xl font-black">Catalogue</div>
        <p class="text-gray-700 text-base">
          View and manage Products, add New Products or Suppliers and Print Stickers.
        </p>
      </div>
      <div class="px-6 pt-4 pb-2">
        <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Continue</button>'.html_safe, catalogue_index_path %>
      </div>
    </div>

    <!--Card 3-->
    <div class="rounded overflow-hidden shadow-lg">
      <!-- <img class="w-full" src="/forest.jpg" alt="Forest"> -->
      <div class="px-6 py-4">
        <div class="mb-4 text-3xl font-black">Inventory</div>
        <p class="text-gray-700 text-base">
          Register new stock received and handle returns.
        </p>
      </div>
      <div class="px-6 pt-4 pb-2">
        <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Continue</button>'.html_safe, inventories_path %>
      </div>
    </div>
  </div>
<% else %>
  <div class="max-w-lg mx-auto mt-16 text-center max-w-sm rounded overflow-hidden shadow-lg p-10">
    <h1 class="mb-4 text-3xl font-black">Welcome to Poskin!!</h1>
    <p class="text-lg leading-snug">why don't you buy this product??</p>
  </div>
<% end %>

app/views/sales/index.html.erb
<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
  <!--Card 1-->
  <div class="rounded overflow-hidden shadow-lg content-center">
    <!-- <img class="w-full" src="/mountain.jpg" alt="Mountain"> -->
    <div class="px-6 py-4">
      <div class="mb-4 text-3xl font-black">Point of Sale</div>
      <p class="text-gray-700 text-base">
        Enter the code or description of the product, number of items and add to order. Proceed and optionally record the customer details. After taking payment confirm the sale (poskin will automatically reduce the quantity for the variant sold) and print receipt
      </p>
    </div>
    <div class="px-6 pt-4 pb-2">
      <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Sell</button>'.html_safe, sales_path %>
    </div>
  </div>
</div>