config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: "home#index"

  resources :sales, only: [:index]
  resources :catalogue, only: [:index]
  resources :suppliers, only: [:index, :new, :create, :show]

  namespace :catalogue do
    resources :suppliers, only: [:index, :new, :create, :show] do
      # collection do
      #   get :select
      #   post :selected
      # end
      resources :products, only: [:index, :new, :create]
    end
  end
  resources :inventories, only: [:index]
end

app/models/supplier.rb
# frozen_string_literal: true

class Supplier < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, :phone, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/catalogue/products_controller.rb
# frozen_string_literal: true

class Catalogue::ProductsController < ApplicationController
  before_action :sanitize_params, only: [:create]
  before_action :product_with_sku_code, only: [:new]

  def new; end

  def create
    @product = supplier.products.new(product_params)
    if @product.save
      redirect_to catalogue_supplier_path(supplier.id)
    else
      render :new
    end
  end

  private

  def product
    @product ||= supplier.products.new
  end

  def product_with_sku_code
    product.sku_code = sku_code
    product
  end

  def sku_code
    @sku_code ||= @product.generated_sku
  end

  def sanitize_params
    params.require(:product).permit(:supplier_id, :accounting_code_id, :title, :description, :notes, :sku_code, :publish, :markup, :cost_price)

    params[:product]['markup'] = markup
    params[:product]['publish'] = publish
    params[:product]['cost_price'] = cost_price
  end

  def unmatched_params
    @unmatched_params ||= params.require(:product).extract!(:publish, :markup, :cost_price)
  end

  def cost_price
    (unmatched_params['cost_price'].gsub(/[^0-9,.]/, '').to_f * 100).to_i
  end

  def markup
    unmatched_params['markup'].gsub(/[^0-9]/, '')
  end

  def publish
    unmatched_params['publish'] == 'Yes'
  end

  def product_params
    params.require(:product).permit(:supplier_id, :accounting_code_id, :title, :description, :notes, :sku_code, :publish, :markup, :cost_price)
  end

  def supplier
    @supplier ||= Supplier.find_by(id: supplier_id)
  end

  def supplier_id
    @supplier_id = params['supplier_id']
  end
end

app/controllers/catalogue/suppliers_controller.rb
# frozen_string_literal: true

class Catalogue::SuppliersController < ApplicationController
  before_action :supplier, only: %i[index create]

  def index; end

  def show
    @supplier = existing_supplier(id: params['id'])
    @products = @supplier.products
  end

  def create
    if existing_supplier.present?
      redirect_to catalogue_supplier_path(existing_supplier.id)
    else
      flash.now.alert = 'Please select a supplier from the list'
      render :index
    end
  end

  private

  def supplier
    @supplier ||= Supplier.new
  end

  def existing_supplier(id: nil)
    supplier_id = id || supplier_params[:id]
    @existing_supplier = Supplier.find_by(id: supplier_id) if supplier_id.present?
  end

  def supplier_params
    params.require(:supplier).permit(:id)
  end
end

app/controllers/catalogue_controller.rb
# frozen_string_literal: true

class CatalogueController < ApplicationController
  def index; end
end

app/controllers/catalogues_controller.rb
# frozen_string_literal: true

class CataloguesController < ApplicationController
  def index; end
end

app/controllers/suppliers_controller.rb
# frozen_string_literal: true

class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end

  def new
    @supplier = Supplier.new
    @gst_rates = TaxRate.all
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to catalogue_suppliers_path
    else
      render :new
    end
  end

  private

  def supplier_params
    params.require(:supplier).permit(:name, :email, :phone, :tax_rate_id, :address_id)
  end
end

app/helpers/catalogue/products_helper.rb
# frozen_string_literal: true

module Catalogue::ProductsHelper
end

app/helpers/catalogue/suppliers_helper.rb
# frozen_string_literal: true

module Catalogue::SuppliersHelper
end

app/helpers/catalogues_helper.rb
# frozen_string_literal: true

module CataloguesHelper
end

app/helpers/suppliers_helper.rb
# frozen_string_literal: true

module SuppliersHelper
end

app/views/catalogue/suppliers/index.html.erb
<main class="p-12 mx-auto text-gray-800 max-w-7xl">
  <%= simple_form_for @supplier, builder: TailwindFormBuilder, class: "mt-6", url: catalogue_suppliers_path do |f| %>
    <%= f.label "Select the Supplier and click Next" %>
    <%= f.collection_select :id, Supplier.order(:name),:id,:name, include_blank: true %>
    <br />
    <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/4 lg:w-1/4 py-2 flex flex-col items-center justify-center">Next</button>'.html_safe, catalogue_suppliers_path, method: :post %>
  <% end %>

    <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/4 lg:w-1/4 py-2 flex flex-col items-center justify-center">Back</button>'.html_safe, catalogue_index_path, method: :get %>
</main>

app/views/catalogue/suppliers/new.html.erb
<main class="p-12 mx-auto text-gray-800 max-w-7xl">
  <% if @supplier.errors.any? %>
    <% @supplier.errors.full_messages.each do |message|%>
       <p class="text-red-700 text-base"><%= message %> </p>
    <%end%>
    <br />
  <%end%>
  <%= simple_form_for @supplier, builder: TailwindFormBuilder, class: "mt-6", url: catalogue_suppliers_path do |f| %>
    <%= f.label "Suppliers Name" %>
    <%= f.text_field :name, placeholder: 'My Supplier Ltd' %>
    <br />
    <%= f.label "Suppliers Email" %>
    <%= f.text_field :email, placeholder: 'person@supplier.com' %>
    <br />
    <%= f.label "Suppliers Contact Number" %>
    <%= f.text_field :phone, placeholder: '0414 444 444' %>
    <br />
    <%= f.label "Notes" %>
    <%= f.text_field :notes, placeholder: 'anything you like in here' %>
    <br />
    <%= f.label "Applicable GST Rate" %>
    <%= f.collection_select :tax_rate_id, TaxRate.order(:name),:id,:name, include_blank: true %>
    <%= f.hidden_field :address_id, :value =>1 %>
    <br />
    <br />
    <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/4 lg:w-1/4 py-2 flex flex-col items-center justify-center">Create Supplier</button>'.html_safe, catalogue_suppliers_path, method: :post %>
    <%= f.submit_button "Create Supplier" %>
<!--     <div class="pt-5">
      <%= f.submit "Begin" %>
    </div> -->
  <% end %>
      <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/4 lg:w-1/4 py-2 flex flex-col items-center justify-center">Back to Suppliers</button>'.html_safe, catalogue_suppliers_path, method: :get %>
</main>

app/views/catalogue/suppliers/show.html.erb
<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
  <div class="max-w-lg mx-auto mt-16 text-center max-w-sm rounded overflow-hidden shadow-lg p-10">
    <h1 class="mb-4 text-3xl font-black"><%= @supplier.name %></h1>
    <p class="text-lg leading-snug"><%= @supplier.email %></p>
  </div>
  <% @products.each do |product| %>
    <%= product.inspect %>
  <% end %>
  <div class="px-6 pt-4 pb-2">
  <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Create New Product</button>'.html_safe, new_catalogue_supplier_product_path(@supplier.id) %>
</div>

</div>