config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: "home#index"

  resources :sales, only: [:index]
  resources :catalogue, only: [:index]
  resources :suppliers, only: [:index, :new, :create, :show]

  namespace :catalogue do
    resources :suppliers, only: [:index, :new, :create, :show] do
      # collection do
      #   get :select
      #   post :selected
      # end
      resources :products, only: [:index, :new, :create]
    end
  end
  resources :inventories, only: [:index]
end

app/models/supplier.rb
# frozen_string_literal: true

class Supplier < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, :phone, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/catalogue/suppliers_controller.rb
# frozen_string_literal: true

class Catalogue::SuppliersController < ApplicationController
  before_action :supplier, only: %i[index create]

  def index; end

  def show
    @supplier = existing_supplier(id: params['id'])
    @products = @supplier.products
  end

  def create
    if existing_supplier.present?
      redirect_to catalogue_supplier_path(existing_supplier.id)
    else
      flash.now.alert = 'Please select a supplier from the list'
      render :index
    end
  end

  private

  def supplier
    @supplier ||= Supplier.new
  end

  def existing_supplier(id: nil)
    supplier_id = id || supplier_params[:id]
    @existing_supplier = Supplier.find_by(id: supplier_id) if supplier_id.present?
  end

  def supplier_params
    params.require(:supplier).permit(:id)
  end
end

app/controllers/suppliers_controller.rb
# frozen_string_literal: true

class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end

  def new
    @supplier = Supplier.new
    @gst_rates = TaxRate.all
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to catalogue_suppliers_path
    else
      render :new
    end
  end

  private

  def supplier_params
    params.require(:supplier).permit(:name, :email, :phone, :tax_rate_id, :address_id)
  end
end

app/helpers/catalogue/suppliers_helper.rb
# frozen_string_literal: true

module Catalogue::SuppliersHelper
end

app/helpers/suppliers_helper.rb
# frozen_string_literal: true

module SuppliersHelper
end

app/views/suppliers/index.html.erb
<html lang="en" class="antialiased">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>DataTables </title>
  <meta name="description" content="">
  <meta name="keywords" content="">
  <link href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" rel=" stylesheet">
  <!--Replace with your tailwind.css once created-->


  <!--Regular Datatables CSS-->
  <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
  <!--Responsive Extension Datatables CSS-->
  <link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet">

  <style>
    /*Overrides for Tailwind CSS */

    /*Form fields*/
    .dataTables_wrapper select,
    .dataTables_wrapper .dataTables_filter input {
      color: #4a5568;
      /*text-gray-700*/
      padding-left: 1rem;
      /*pl-4*/
      padding-right: 1rem;
      /*pl-4*/
      padding-top: .5rem;
      /*pl-2*/
      padding-bottom: .5rem;
      /*pl-2*/
      line-height: 1.25;
      /*leading-tight*/
      border-width: 2px;
      /*border-2*/
      border-radius: .25rem;
      border-color: #edf2f7;
      /*border-gray-200*/
      background-color: #edf2f7;
      /*bg-gray-200*/
    }

    /*Row Hover*/
    table.dataTable.hover tbody tr:hover,
    table.dataTable.display tbody tr:hover {
      background-color: #ebf4ff;
      /*bg-indigo-100*/
    }

    /*Pagination Buttons*/
    .dataTables_wrapper .dataTables_paginate .paginate_button {
      font-weight: 700;
      /*font-bold*/
      border-radius: .25rem;
      /*rounded*/
      border: 1px solid transparent;
      /*border border-transparent*/
    }

    /*Pagination Buttons - Current selected */
    .dataTables_wrapper .dataTables_paginate .paginate_button.current {
      color: #fff !important;
      /*text-white*/
      box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06);
      /*shadow*/
      font-weight: 700;
      /*font-bold*/
      border-radius: .25rem;
      /*rounded*/
      background: #667eea !important;
      /*bg-indigo-500*/
      border: 1px solid transparent;
      /*border border-transparent*/
    }

    /*Pagination Buttons - Hover */
    .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
      color: #fff !important;
      /*text-white*/
      box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06);
      /*shadow*/
      font-weight: 700;
      /*font-bold*/
      border-radius: .25rem;
      /*rounded*/
      background: #667eea !important;
      /*bg-indigo-500*/
      border: 1px solid transparent;
      /*border border-transparent*/
    }

    /*Add padding to bottom border */
    table.dataTable.no-footer {
      border-bottom: 1px solid #e2e8f0;
      /*border-b-1 border-gray-300*/
      margin-top: 0.75em;
      margin-bottom: 0.75em;
    }

    /*Change colour of responsive icon*/
    table.dataTable.dtr-inline.collapsed>tbody>tr>td:first-child:before,
    table.dataTable.dtr-inline.collapsed>tbody>tr>th:first-child:before {
      background-color: #667eea !important;
      /*bg-indigo-500*/
    }
  </style>



</head>

<body class="bg-gray-100 text-gray-900 tracking-wider leading-normal">


  <!--Container-->
  <div class="container w-full md:w-4/5 xl:w-3/5  mx-auto px-2">

    <!--Title-->
    <h1 class="flex items-center font-sans font-bold break-normal text-indigo-500 px-2 py-8 text-xl md:text-2xl">
      Suppliers
    </h1>

    <!--Card-->
    <div id='recipients' class="p-8 mt-6 lg:mt-0 rounded shadow bg-white">
      <table id="example" class="stripe hover" style="width:100%; padding-top: 1em;  padding-bottom: 1em;">
        <thead>
          <tr>
            <th data-priority="1">Name</th>
            <th data-priority="2">Email</th>
            <th data-priority="3">Phone</th>
            <th data-priority="4">Address</th>
            <th data-priority="5">Tax Rate</th>
            <th data-priority="6">Notes</th>
          </tr>
        </thead>
        <tbody>
          <% @suppliers.each do |supplier| %>
          <tr>
            <td><%= supplier.name %></td>
            <td><%= supplier.email %></td>
            <td><%= supplier.phone %></td>
            <td><%= supplier.address_id %></td>
            <td><%= supplier.tax_rate_id %></td>
            <td><%= supplier.notes %></td>
          </tr>
          <% end %>
        </tbody>

      </table>


    </div>
    <!--/Card-->


  </div>
  <!--/container-->
  <br />
  <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/4 lg:w-1/4 py-2 flex flex-col items-center justify-center">Create New Supplier</button>'.html_safe, new_supplier_path %>
  <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/4 lg:w-1/4 py-2 flex flex-col items-center justify-center">Back to Catalogue</button>'.html_safe, catalogue_index_path %>



  <!-- jQuery -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

  <!--Datatables -->
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
  <script>
    $(document).ready(function() {

      var table = $('#example').DataTable({
          responsive: true
        })
        .columns.adjust()
        .responsive.recalc();
    });
  </script>

</body>

</html>

app/views/suppliers/new.html.erb
<main class="p-12 mx-auto text-gray-800 max-w-7xl">
  <% if @supplier.errors.any? %>
    <% @supplier.errors.full_messages.each do |message|%>
       <p class="text-red-700 text-base"><%= message %> </p>
    <%end%>
    <br />
  <%end%>
  <%= simple_form_for @supplier, builder: TailwindFormBuilder, class: "mt-6", url: suppliers_path do |f| %>
    <%= f.label "Suppliers Name" %>
    <%= f.text_field :name, placeholder: 'My Supplier Ltd' %>
    <br />
    <%= f.label "Suppliers Email" %>
    <%= f.text_field :email, placeholder: 'person@supplier.com' %>
    <br />
    <%= f.label "Suppliers Contact Number" %>
    <%= f.text_field :phone, placeholder: '0414 444 444' %>
    <br />
    <%= f.label "Notes" %>
    <%= f.text_field :notes, placeholder: 'anything you like in here' %>
    <br />
    <%= f.label "Applicable GST Rate" %>
    <%= f.collection_select :tax_rate_id, TaxRate.order(:name),:id,:name, include_blank: true %>
    <%= f.hidden_field :address_id, :value =>1 %>
    <br />
    <br />
    <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/4 lg:w-1/4 py-2 flex flex-col items-center justify-center">Create Supplier</button>'.html_safe, suppliers_path, method: :post %>
  <% end %>
      <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/4 lg:w-1/4 py-2 flex flex-col items-center justify-center">Back to Suppliers</button>'.html_safe, suppliers_path, method: :get %>
</main>